# Generated by Django 5.1.5 on 2025-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('fulltime', 'Fulltime'), ('remote', 'Remote'), ('contract', 'Contract'), ('wfh', 'WFH')], default='fulltime', max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
