# Generated by Django 5.1.5 on 2025-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_product_image_url_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('text_1', models.TextField()),
                ('text_2', models.TextField()),
                ('text_3', models.TextField()),
            ],
        ),
    ]
